# Generated by Django 3.2.25 on 2024-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_tarea_fecha_creación'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='building',
            field=models.CharField(choices=[('850', '850'), ('851', '851')], max_length=3),
        ),
    ]
