# Generated by Django 3.2.25 on 2024-07-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20240712_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroom',
            old_name='revisado',
            new_name='publicar',
        ),
    ]
