# Generated by Django 3.2.25 on 2024-07-13 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_revisado_bathroom_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='floor',
            field=models.CharField(choices=[('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-07-13'),
        ),
    ]
