# Generated by Django 3.2.25 on 2024-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_revisado_bathroom_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bathroom',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-07-14'),
        ),
    ]
