# Generated by Django 3.2.25 on 2024-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20240713_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-07-15'),
        ),
    ]
