# Generated by Django 3.2.25 on 2024-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-07-15'),
        ),
    ]
