# Generated by Django 3.2.25 on 2024-07-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20240715_1140'),
        ('todoapp', '0011_cleaning'),
    ]

    operations = [
    ]
