# Generated by Django 3.2.25 on 2024-07-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_merge_0009_auto_20240715_1140_0011_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='bathroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_reviews', to='todoapp.bathroom'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-07-18'),
        ),
    ]
